apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
        name: captain-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: captain-deployment
  minReplicas: 7
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization 
        averageUtilization: 60 
